name: Test Suite

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  contracts:
    name: Smart Contract Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./caliguland/contracts
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge tests
        run: |
          forge install
          forge test -vv

      - name: Run Forge coverage
        run: forge coverage

  game-server:
    name: Game Server Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./caliguland/caliguland-game
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: caliguland/caliguland-game/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [contracts, game-server]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Start services
        run: |
          cd caliguland
          docker-compose up -d caliguland-game caliguland-auth
          sleep 10

      - name: Run E2E tests
        run: |
          cd caliguland
          bun run scripts/test-scripted-game.ts

      - name: Cleanup
        if: always()
        run: |
          cd caliguland
          docker-compose down

  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check Solidity formatting
        run: |
          cd caliguland/contracts
          forge fmt --check

      - name: Check TypeScript formatting (Game Server)
        run: |
          cd caliguland/caliguland-game
          npm ci
          npm run lint || echo "No lint script configured"

